### ISSUE TITLE
Rename variables in ICRA.sc2map 

### ISSUE THREAD

**Issue by SoyGema** [PeterLayton/ICRA2018_SC2env_RL#2]
Hi there!
I would like to include your mini game in the community pySC2 repository I am building . 
https://github.com/SoyGema/pySC2_minigames

However, when opening the .sC2map file, the variables rename to a non chinese  language it becomes really hard to distinguish in between them as the translation goes to 20/21 string with consonants like "dbhiinjhlktfghhnbb" .

Would you mind to **rename the variables in the map editor** so it might become more readable for others to read / transform ?  ^^ 

Many thanks for taking part of #pysc2 community and publish your repository !

**Comment by PeterLayton** [comment]
ok, thanks for your suggestions. I remember I encounter this problem before.
